### ISSUE TITLE
coookie

### ISSUE THREAD

**Issue by vivaxof** [medialab/minet#1007]
Hello,

This is my first time using minet. I have been trying  to launch a simple request to extract posts from as follow  twitter
`!minet twitter scrape tweets "from:medialab_ScPo" --rcfile .minetrc`

I have the following error message

```
You piped the result of your command into stdout.
Stdout piping (">") is known to be unreliable on Windows shells (cmd.exe, 
PowerShell)
and can sometimes result in corrupted data.

Are you sure you know what you are doing?
If you are not sure, please use the --output flag instead.

Scraping ----------- 0/1 queries -  (?/s)                                      
â ‹  0/? tweets  (?/s) total: 0 tweets                                           
Scraping ----------- 0/1 queries -  (?/s)                                      
â ‹  0/? tweets  (?/s) total: 0 tweets                                           
Invalid Twitter cookie!
Try giving another browser to --cookie and sure you are correctly logged in.
```

to create .minetrc file (saved as json format) i used the following information

```
twitter:
  cookie: "MY_TWITTER_COOKIE"  => using the auth_token cookie from my browser on x.com site
  api_key: "MY_API_KEY" 
  api_secret_key: "MY_API_SECRET_KEY" 
  access_token: "MY_ACCESS_TOKEN" 
  access_token_secret: "MY_ACCESS_TOKEN_SECRET" 
```

I am using the free api from X.

Where is my error ? thanks in advance for your help.
