### ISSUE TITLE
What about attr with sels

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#108]
```yml
  themes:
    sels: "#grid-course a[href^='/subject/']"
    eval: "'|'.join(e.get('href') for e in elements)"
```
