### ISSUE TITLE
Crawler deadlock issues

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#156]
This crawler causes a deadlock that is probably caused by some subtle `QueueIterator` bug.

```yml
---
start_urls:
  - 'https://op.europa.eu/en/search-results?p_p_id=eu_europa_publications_portlet_search_result_summary_SearchResultSummaryPortlet_INSTANCE_Ja6zoyQuPn9a&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&queryText=%22artificial%20intelligence%22&keywordOptions=EXACT&facet.collection=EUPub&facet.collection=EUDir&facet.collection=EULex&facet.collection=EUWebPage&facet.collection=EUSummariesOfLegislation&sortBy=RELEVANCE-DESC&SEARCH_TYPE=ADVANCED&QUERY_ID=171539253&&language=en&resultsPerPage=50'
  - 'https://op.europa.eu/en/browse-by-subject?p_p_id=eu_europa_publications_portlet_search_result_summary_SearchResultSummaryPortlet_INSTANCE_J3bVc3AR9wJT&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&facet.eurovoc.subject=4253&facet.collection=EUPub&facet.collection=EULex&facet.collection=EUWebPage&facet.collection=EUSummariesOfLegislation&selectedSubjectId=4253&sortBy=RELEVANCE-DESC&SEARCH_TYPE=BROWSE_BY_SUBJECT&QUERY_ID=171539420&&language=en&resultsPerPage=50'
next:
  scraper:
    sel: .list-item.selected + .list-item > a
    item:
      attr: href
scraper:
  iterator: a.documentDetailLink
  fields:
    url: href
```
