### ISSUE TITLE
Validation issues with filter_eval

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#334]
```yml
---
fields:
    id:
        sel: 'p:-soup-contains("ID:")'
        eval: |
            return value.split('ID:')[-1].strip()
    url:
        get_context: line.value
    title:
        sel: h1
    published:
        sel: 'p:-soup-contains("Published:")'
        eval: |
            return value.split('Published:')[-1].strip()
    analysts:
        sel: 'p:-soup-contains("Analyst(s):")'
        eval: |
            return value.split('Analyst(s):')[-1].strip()
    summary:
        iterator: h5:-soup-contains("Summary") ~ p
        item: display_text
        filter_eval: |
            return (
                "Published:" not in value and
                "ID:" not in value and
                "Analyst(s):" not in value
            )
        join: "\n\n"
```
