### ISSUE TITLE
Twitter API scrapper seems down as it is not fetching tweets, when tried to fetch for few custom or generic queries 

### ISSUE THREAD

**Issue by vatsal-kavida** [medialab/minet#700]

**Comment by Yomguithereal** [comment]
Hello @vatsal-kavida,

Twitter search is not available any more since yesterday if you are not logged in. I am trying to find some countermeasure by letting user rely on their connexion to a Twitter account but it may prove difficult or impossible if accounts get banned for instance. So there might be no solution. Just hang tight for now.

**Comment by Yomguithereal** [comment]
v1.0.0-a18 is now released and offers a way to scrape while logged in to the website using the `--cookie` flag. Just be advised that basically Twitter now knows who is scraping them and I have no guarantees they won't try to ban accounts in the future.

**Comment by tloops329384** [comment]
Hi @Yomguithereal I could not understand how to use the Twitter cookie to scrape tweets as usual... I signed in my Twitter account in firefox and add --cookie Firefox after my tw scrape query. What is wrong ? 
Thank you so much

**Comment by Yomguithereal** [comment]
I cannot tell you what is wrong with the information you gave me. Did you correctly upgrade `minet` to the latest version? What command did you run? What happened? Did you see an error?

**Comment by tloops329384** [comment]
I've correctly upgraded minet to version 1.0.0-a26. My command was : (see picture)
![Capture](https://github.com/medialab/minet/assets/112090034/7b743aa9-2a0a-480e-bfea-6b3c55955bc9)

**Comment by Yomguithereal** [comment]
As the command states, the cookie given is invalid. The name of the browser should be lower-cased. "chrome" or "firefox", not "Chrome". But I guess I should be fuzzy there so that people don't stumble on this.

**Comment by tloops329384** [comment]
Thank you for answering. In fact, even with lower case, the command doesn't work. I'm still logged in Twitter on Chrome. The error is different... but still doesn't work. 

![Capture](https://github.com/medialab/minet/assets/112090034/73607ddb-2c9d-45bf-a578-6e7dd9c61560)

**Comment by Yomguithereal** [comment]
This is an error of the `browser-cookie3` library there. You can either try to upgrade the library by running `pip install -U browser-cookie3` if you are not using the standalone version. Or you can try another browser. Else you can also open a browser, and copy the cookie directly if you know how to use the network tab of the developer tool and pass it to `--cookie` directly instead of the name of the browser.

**Comment by tloops329384** [comment]
Hi @Yomguithereal, sorry to come back "à la charge", but I tried everything I could to find the good cookie in my Firefox developer tab to be past in my ubuntu console... Could you give a tip to get around the error I mentioned earlier ? Or either embellish the readme with some indications ? 
For the moment I can't retrieve any tweet anymore.
Thank you very much 
ps : do understand if you don't have time to answer

**Comment by Yomguithereal** [comment]
@tloops329384 if you correctly found the cookie string in the developer console of Firefox (as an example it should look like something like this probably):

```txt
ads_prefs="HBISAAA="; remember_checked_on=1; auth_token=f30f5e42f8334ed45ab8bf3f045e343b76e8984c; ct0=ba5e1f7e2119261a330340f01bff14916512382908f8ebad02e03da47b11765f11d53217b1cfcafbd0fd97f889658dfad76aa1ed4aa9f8072e4caa56687d4d0963e710604c3f56e3203aac00837d6e60d; dnt=1; eu_cn=1; d_prefs=MjoxLGNNqvfEVnNlbnRfdmVyc2lvbjoyLHRleHRfdmVyc2lvbjoxMDAw; guest_id=v1%3A161093553675879117; des_opt_in=N; night_mode=0; twid=u%3D156537623927; g_state={"i_p":16802363278593,"i_l":2}
```

This is my cookie for instance (mangled, of course, so I don't leak my actual credentials). The important part is the `ct0`stuff, the `guest_id` and the `auth_token`.

It can be hard to paste directly within a shell because of the quotes etc. But what you can try also is to go the `.minetrc.yml` way as explained [here](https://github.com/medialab/minet/blob/master/docs/cli.md#minetrc-config-files).

You would then have a config file looking like this:

```yml
---
twitter:
  cookie: ads_prefs="HBISAAA="; remember_checked_on=1; auth_token=f30f5e42f8334ed45ab8bf3f045e343b76e8984c; ct0=ba5e1f7e2119261a330340f01bff14916512382908f8ebad02e03da47b11765f11d53217b1cfcafbd0fd97f889658dfad76aa1ed4aa9f8072e4caa56687d4d0963e710604c3f56e3203aac00837d6e60d; dnt=1; eu_cn=1; d_prefs=MjoxLGNNqvfEVnNlbnRfdmVyc2lvbjoyLHRleHRfdmVyc2lvbjoxMDAw; guest_id=v1%3A161093553675879117; des_opt_in=N; night_mode=0; twid=u%3D156537623927; g_state={"i_p":16802363278593,"i_l":2}
```

And depending on where you place the config file, you might need the `--rcfile` flag or not (this is explained in the beforementioned documentation).
